library("dplyr")
library("shiny")
library('magrittr')
library('shinydashboard')
library('DT')
library('googleVis')
library('reshape2')
library('tidyr')

by_years = read.csv('DATA/by_years.csv', header = TRUE)
by_species = read.csv('DATA/by_species.csv', header = TRUE)
by_Norway = read.csv('DATA/by_norway.csv', header = TRUE)

countries <- distinct(by_years %>% select(., Country))
species <- distinct(by_years %>% select(., Species))
years_a <- distinct(by_species %>% select(., Year))